language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - alexey.dushenin@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: JeK21Iy09nwX39LzFGTKeoTPsr/wTQ9YD2MxvyjvXCuB7dJdjWssXA+/PSQkWFdc05GK7wKieTkpLNNuibk9lahf6Qw7AadoAmLvbiMy2k9gLfHuTJhEbjF2g0lQCrJDd7LCD7O2B99UcpCxZV/eD0cLJ1EAAsHOK720ATF0pIOuxfO6bF9rbJdYxOOeim5pFoGMNK2/NNK1q/DYnst1ojB/4rA+8sz4nZWbShYJTqNDaXis+m9NZEZwJ91uax4DwDRTD/dIn5f4oHymqCHHDce1whNm3IBaZiTnZaMuh5SUIXqG4cSbFzTIob4GKsga/mlQQhrH1GArrZgB+oaJKc/GitC6hZ9/gj3kGBDoegK0TG5doTX6+vpkrS8hRsxB6U/dAiNZlPzj/Ir8SAh9PbjEntCroqwaV0Df6y6bmPvlRzio99RSSQsGcHwTgot/wr4whlpHAg0wsZGLSMfMsyEnGKLgopNGmG3m/6N2JyQOsHKgJ4Y4e3nMFv4S7V+IbQRDb70KGwpzYkZtti+T2uvsGwoX5QpsYMA1atJIyXZrIErA/a3YOZC2W8BstQsaVAMPc3iMn08amogKO4lvm7g8AHAl0+8vYFVP4qSK6SNO3+fT7I7qmyJqUHDZSP+revW5Ins7wxKzOXtiOGcMPqRlOEYEhzwartVC/ATYA68=
  - secure: hnfPhRGhDoOyNgK6ajiZ7vA+HdLIvKquj/IGh6TQtiSLLjsok74PjqCs3VHnQ2FCkdFP13Y3bhnI3sDuOC4xEskz17sMK5tvAuEbgSTqbu+GmjJU052kD526Z1Mfme0EuowGfXz37vtWNEb5sTlVSb9Ra1XE+to2xYSXZsYIlVdQ1iHoc0IikHlMXy/7eKNxKqM6i13kJOfpPcXFtkwg4355VMo3Att87tHDm+KkWzGajhsjI4gyg9TrdxcZgNf1XZZOuIO5uh3BqtPuqYkg5DMSybcGSlARiAUpAQBIZdzQkgNZdUnNvDKgOYZAiQH8Zbn0CsDlBm/ZsbpkYz7CqTM4MgBcOEg0JPNetejWEqcI5BWmaKmsdVFZJFYPRu1AFFMQ3WNYCf5yg4D5jo3P7hBTwWykddAwN4ECN45KMGJ3qzXoCvhUJJw4CMtJTMSR8umAz9HcSpl34/uDAdaS8Jw54EkO2tOMyLjh0YAtNCZvxxW78ikc++tbd8JfxoCGynWzrmgNKxqi3LtkGahCCRm7ptMsywVBqi3F0KCPlbG/aP7d+lgxsvTJLUlhj2MFYfhr5n2b+SMzQnvtxgJB6TRrqyp61rt5l1Uvln1OxQkTI1mssZ2vx6/ifhzbnT18RbxhXd7ie56l1QtI4gM2rtOOUOIYWmqjWn5ge0RU7WU=
before_install:
- export BUILD_NAME=1.0
script:
- sh travis/build.sh
- sh travis/push_to_docker_hub.sh
