spring:
  application:
    name: servicediscovery
  cloud:
    config:
      uri: http://config-server:8888
      enabled: true

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
