zuul:
  prefix: /api

spring:
  application:
    name: zuulserver
  profiles:
    active:
      default
  cloud:
    config:
      uri: http://config-server:8888
      enabled: true
  zipkin:
    baseUrl:  http://zipkin:8762


server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

management.security.enabled: false

logging:
    pattern:
        console: "-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %X{correlation-id} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

